version: "3.9"

services:
    hifumi:
        build:
            context: ./
            dockerfile: Dockerfile

    db:
        image: mongo
        ports:
            - "27017"
        command: mongod --quiet --logpath /dev/null --bind_ip_all
