name: Continuous Integration

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    BOT_ID: ${{ secrets.BOT_ID }}

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup bun
              uses: oven-sh/setup-bun@v1

            - name: Install Dependencies
              run: bun install --production --ignore-scripts

            - name: Deploy
              run: bun run deploy
