# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy Slash Commands

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    deploy:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.12.0]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: Load environment variables
              id: dotenv
              shell: bash
              uses: falti/dotenv-action@v1.0.1

            - name: Set up environment variables
              run: |
                  if [BOT_TOKEN_PROD != ""]; then
                    echo "BOT_TOKEN=$BOT_TOKEN_PROD" >> $GITHUB_ENV
                  fi
                  if [BOT_ID != ""]; then
                    echo "BOT_ID=$BOT_ID" >> $GITHUB_ENV
                  fi
            - name: Install Dependencies
              run: npm ci
            - name: Deploy
              run: npm run deploy
